name: Frontend CI/CD

on:
  workflow_dispatch:
  push:
    branches:
      - dev
      - staging
      - main
    paths:
      - 'frontend/**'

jobs:
  frontend:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: learningsuresh/tasks-app-frontend
      SONAR_ORG_KEY: suresh-dev-05
      SONAR_PROJECT_KEY: suresh-dev-05_tasks-app

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set environment
        id: env
        run: |
          if [[ "${GITHUB_REF##*/}" == "main" ]]; then
            echo "ENV=prod" >> $GITHUB_ENV
            echo "TAG=prod" >> $GITHUB_ENV
          elif [[ "${GITHUB_REF##*/}" == "staging" ]]; then
            echo "ENV=staging" >> $GITHUB_ENV
            echo "TAG=staging" >> $GITHUB_ENV
          else
            echo "ENV=dev" >> $GITHUB_ENV
            echo "TAG=dev" >> $GITHUB_ENV
          fi

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.11.1

      - name: Install, Test & Build
        run: |
          cd frontend
          npm ci
          npm run test -- --coverage
          npm run build

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          projectBaseDir: backend
          args: >
            -Dsonar.projectKey=${{env.SONAR_PROJECT_KEY}}
            -Dsonar.organization=${{env.SONAR_ORG_KEY}}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t $IMAGE_NAME:$TAG ./frontend

      - name: Run Trivy scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.IMAGE_NAME }}:${{ env.TAG }}
          scanners: vuln
          format: table
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: os,library
          severity: HIGH,CRITICAL

      - name: Push Docker image
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push $IMAGE_NAME:$TAG
